# Generated by Django 4.1.5 on 2023-01-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigacion",
            name="categorias_investigacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.categoria_inv",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="investigacion",
            name="nombre_investigacion",
            field=models.CharField(
                max_length=150, verbose_name="Tipo de investigacion"
            ),
        ),
        migrations.AlterField(
            model_name="investigacion",
            name="titulo",
            field=models.CharField(max_length=150, verbose_name="Titulo"),
        ),
    ]
