# Generated by Django 4.1.5 on 2023-01-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_investigacion_categorias_investigacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investigacion",
            old_name="uploadedFile",
            new_name="archivo",
        ),
        migrations.RenameField(
            model_name="investigacion",
            old_name="ImagenD",
            new_name="imagen_d",
        ),
        migrations.RenameField(
            model_name="investigacion",
            old_name="linkedin",
            new_name="link",
        ),
        migrations.RenameField(
            model_name="investigacion",
            old_name="Resumen",
            new_name="resumen",
        ),
        migrations.RemoveField(
            model_name="investigacion",
            name="nombre_investigacion",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="cursos",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="estudios_p",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="estudios_s",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="experiencia",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="universidad",
        ),
    ]
