# Generated by Django 4.1.5 on 2023-01-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0003_rename_uploadedfile_investigacion_archivo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_insti",
                    models.CharField(
                        choices=[
                            ("primaria", "Primaria"),
                            ("secundaria", "Secundaria"),
                            ("tercer", "Tercer"),
                        ],
                        max_length=100,
                        verbose_name="Nombre Institución",
                    ),
                ),
                (
                    "fecha_gra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Graduación"
                    ),
                ),
                (
                    "fecha_reg",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "num_reg",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Número de Registro",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="TituloPDF"),
                ),
            ],
        ),
    ]
