# Generated by Django 4.1.5 on 2023-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0004_estudio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, verbose_name="Titulo Curso"),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre Organizador",
                    ),
                ),
                (
                    "horas",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        verbose_name="Horas del Curso",
                    ),
                ),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            ("asistencia", "Asistencia"),
                            ("aprobacion", "Aprobacion"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Certificado",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_emp",
                    models.CharField(max_length=150, verbose_name="Nombre Empresa"),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cargor"
                    ),
                ),
                (
                    "actividades",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Actividades que realiza",
                    ),
                ),
                ("fecha_inicio_e", models.DateField()),
                ("fecha_fin_e", models.DateField()),
            ],
        ),
    ]
