# Generated by Django 4.1.5 on 2023-01-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0005_curso_experiencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="tipo_cursos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.curso",
                verbose_name="Cursos",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="tipo_estudios",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.estudio",
                verbose_name="Estudios",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="tipo_experiencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.experiencia",
                verbose_name="Experiencia",
            ),
        ),
    ]
