# Generated by Django 4.1.5 on 2023-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0006_autor_tipo_cursos_autor_tipo_estudios_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="tipo_cursos",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="tipo_estudios",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="tipo_experiencia",
        ),
        migrations.AddField(
            model_name="autor",
            name="cursos",
            field=models.ManyToManyField(blank=True, to="administracion.curso"),
        ),
        migrations.AddField(
            model_name="autor",
            name="estudios",
            field=models.ManyToManyField(blank=True, to="administracion.estudio"),
        ),
        migrations.AddField(
            model_name="autor",
            name="experiencias",
            field=models.ManyToManyField(blank=True, to="administracion.experiencia"),
        ),
    ]
