# Generated by Django 4.1.5 on 2023-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion",
            "0007_remove_autor_tipo_cursos_remove_autor_tipo_estudios_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="estudio",
            name="tipo_estu",
            field=models.CharField(
                choices=[
                    ("primaria", "Primaria"),
                    ("secundaria", "Secundaria"),
                    ("tercer", "Tercer"),
                ],
                default=2,
                max_length=100,
                verbose_name="Tipo de Estudio ",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estudio",
            name="nombre_insti",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre Institución"
            ),
        ),
    ]
