# Generated by Django 4.1.5 on 2023-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0008_estudio_tipo_estu_alter_estudio_nombre_insti"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudio",
            name="tipo_estu",
        ),
        migrations.AddField(
            model_name="estudio",
            name="insti",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre Institución"
            ),
        ),
        migrations.AlterField(
            model_name="estudio",
            name="nombre_insti",
            field=models.CharField(
                choices=[
                    ("primaria", "Primaria"),
                    ("secundaria", "Secundaria"),
                    ("tercer", "Tercer"),
                ],
                default=1,
                max_length=100,
                verbose_name="Tipo de estudio ",
            ),
            preserve_default=False,
        ),
    ]
