# Generated by Django 4.1.5 on 2023-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0009_remove_estudio_tipo_estu_estudio_insti_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="cursos",
            field=models.ManyToManyField(
                blank=True, related_name="curso", to="administracion.curso"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="estudios",
            field=models.ManyToManyField(
                blank=True, related_name="estudio", to="administracion.estudio"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="experiencias",
            field=models.ManyToManyField(
                blank=True, related_name="experiencia", to="administracion.experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="investigaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="investigacion",
                to="administracion.investigacion",
            ),
        ),
    ]
